services:
  lb:
    image: haproxy:2.8-alpine
    platform: linux/amd64
    ports:
      - "9999:9999"
    volumes:
      - ./deploy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - lb_sockets:/run/sockets
    depends_on:
      - api-1
      - api-2
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "32M"

  api-1:
    image: peregrinno/heimdall:latest
    platform: linux/amd64
    environment:
      LISTEN: "unix:/run/sockets/api-1.sock"
      REFERENCE_PATH: /data/references.rbin
      DATA_DIR: /data
      KNN_WORKERS: "2"
    volumes:
      - ./data:/data:ro
      - lb_sockets:/run/sockets
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "150M"

  api-2:
    image: peregrinno/heimdall:latest
    platform: linux/amd64
    environment:
      LISTEN: "unix:/run/sockets/api-2.sock"
      REFERENCE_PATH: /data/references.rbin
      DATA_DIR: /data
      KNN_WORKERS: "2"
    volumes:
      - ./data:/data:ro
      - lb_sockets:/run/sockets
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "150M"

volumes:
  lb_sockets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
